### ISSUE TITLE
Typing error in masonry-layout.d.ts

### ISSUE THREAD

**Issue by kaseyhinton** [andreasbm/masonry-layout#5]
First off, great work on this component! It is super useful :) Thank you!!

I am getting error 'get' and 'set' accessor must have the same type for the getter and setter of cols.
I am using the ts compiler flag `--skipLibCheck` to ignore it as a workaround. My typescript version is 3.7.3. Let me know if you need any other additional details or if you have an idea for a better set up for my typescript configuration to get around this error. Thanks!

![typing](https://user-images.githubusercontent.com/20712428/73967496-3ef99780-48d5-11ea-98a4-a8abb8a3b021.PNG)

**Comment by andreasbm** [comment]
Hi Kasey! Thanks a lot for opening this issue 👍 I'm glad that you like the component and find it useful! I have fixed the typings so everything should be working as intended in `v2.0.7`. If you are still experiencing the same problems with the new version, please reopen this issue and I'll look into it again ⭐️
